import { useEffect, useState } from 'react'
import { useRouter } from 'next/router';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter();

  useEffect(() => {
    const handleRouteChange = () => {
      // Đặt vị trí cuộn trang về 0 mỗi khi chuyển trang
      window.scrollTo(0, 0);
    };

    // Lắng nghe sự kiện routeChangeComplete sau khi chuyển trang
    router.events.on('routeChangeComplete', handleRouteChange);

    return () => {
      // Huỷ lắng nghe sự kiện khi component unmount
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
